name: publish and release package

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to use'
        required: true

jobs:
  release_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: poetry build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0 python3-opencv
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry with docs
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies with docs
        run: |
          poetry install --with docs
          poetry install --no-root
      - name: Build docs
        run: poetry run sphinx-build -b html docs/source docs/build/html
      - name: Zip artifacts
        run: |
          cd docs/build
          zip -r docs.zip html/
      - name: Debugging
        run: |
          pwd
          ls -la
          ls -la docs/build
          ls -la docs/build/html
      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./docs/build/html

  build_executable:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: macos-latest # arm64 macOS
          - os: macos-13 # x86_64 macOS
          - os: ubuntu-22.04 # x86_64 linux, oldest available GH runner. Older libc for maximal compatibility
          - os: ubuntu-22.04-arm # arm linux build
    steps:
      - name: Install apt dependencies
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libglib2.0-0 python3-opencv
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
          pip install pyinstaller pillow
      - name: Build executable
        shell: bash
        run: ./executable/make.sh
      - name: Rename executable build (mac)
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
        run: mv dist/FairSenseAI.tgz dist/FairSenseAI-${{ runner.os }}-${{ runner.arch }}.tgz
      - name: Rename executable build (windows)
        shell: bash
        if: matrix.os == 'windows-latest'
        run: mv "dist/FairSenseAI/FairSenseAI.exe" "dist/FairSenseAI/FairSenseAI-${{ runner.os }}-${{ runner.arch }}.exe"
      - name: Debugging
        shell: bash
        run: |
          pwd
          ls -la
          ls -la ./dist
          ls -la ./dist/FairSenseAI
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: FairSenseAI-${{ runner.os }}-${{ runner.arch }}
          path: ./dist/*

  release_github:
    needs: [build_docs, build_executable]
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ github.event.inputs.tag }}
          artifacts: |
            dist/FairSenseAI/FairSenseAI-*.exe
            dist/FairSenseAI-*.tgz
            docs/build/docs.zip
          generateReleaseNotes: true
